### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by GrpeApple** [brunoluiz/grammarly-markdown-extension#15]
> # Grammarly to Markdown extension
> 
> 🖋 Convert Grammarly to Markdown (browser extension)
>
> ## Usage
>
>  1. Open any document in Grammarly -- URL might be
>  1. https://app.grammarly.com/ddocs/*

https://app.grammarly.com/ddocs/* to https://app.grammarly.com/docs/*

**Comment by brunoluiz** [comment]
As you can see in the following screenshot, it should be directing you to `ddocs`. Where have you found `/docs`?

![Screenshot 2020-11-09 at 16 28 42](https://user-images.githubusercontent.com/3219330/98568138-ac918480-22a8-11eb-9e89-5464776fc0b5.png)

**Comment by GrpeApple** [comment]
Huh, strange.
Maybe I have dyslexia.
Anyway, my mistake.
