### ISSUE TITLE
cann't  understand how how it work

### ISSUE THREAD

**Issue by qingzi02010** [brunoluiz/grammarly-markdown-extension#30]
After I finished editing with markdown syntax in https://app.grammarly.com/ddocs/*, I clicked the Google Chrome extension plugin "Grammarly to markdown", I really get the message "copied to clipboard".  But when I pasted to the .md file, it's not the correct markdown format. I am wondering what operation I missed or whether I did the wrong operation.

**Comment by brunoluiz** [comment]
> After I finished editing with markdown syntax

It doesn't convert markdown to markdown. It converts what text you have in Grammarly into Markdown. This is especially useful if you:

1. Use H1 and H2 tags
2. Use any styling formatting (bold, italic etc)
3. Add links
4. Write lists (albeit there is an issue with sub-items on a list)

It converts this:
![Screenshot 2021-12-29 at 17 08 29](https://user-images.githubusercontent.com/3219330/147686690-76ff98a4-10b3-4b35-b949-fb37951a2c56.png)

Into this:

```markdown
# Grammarly to Markdown: doc title

## H1: Lorem ipsum

[Lorem ipsum dolor sit amet (link)][1], consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

### H2 Unordered List:

- **(Bold) Feugiat in fermentum** posuere urna nec tincidunt praesent semper. Nisi vitae suscipit tellus mauris a diam.
- **(Bold) Turpis egestas** maecenas pharetra convallis posuere morbi leo urna. Nibh tortor id aliquet lectus proin nibh nisl.

### H2 Ordered List:

1.  **(Bold) Feugiat in fermentum** posuere urna nec tincidunt praesent semper. Nisi vitae suscipit tellus mauris a diam.
2.  **(Bold) Turpis egestas** maecenas pharetra convallis posuere morbi leo urna. Nibh tortor id aliquet lectus proin nibh nisl.

_(Italic) Odio ut enim blandit volutpat maecenas volutpat. Elementum sagittis vitae et leo duis ut diam quam nulla._

[1]: https://loremipsum.io/
```

**Comment by brunoluiz** [comment]
>  it's not the correct markdown format.

There are some options in the extension settings (right-click on the extension icon). That let's you customise some of its markdown export settings.

**Comment by brunoluiz** [comment]
Thinking again here, it might be useful to adjust the readme and the chrome extension page with more details about that. Does my replies answer your questions?

**Comment by qingzi02010** [comment]
Yes, it works now. It didn't work because I directly write the text in markdown grammar instead of using the bottom toolbox. Thanks for your answer which really helped me out!
