### ISSUE TITLE
🚨 Unexpected error

### ISSUE THREAD

**Issue by chris-short** [brunoluiz/grammarly-markdown-extension#33]
Is there a log I can check to help troubleshoot?

**Comment by sinaatalay** [comment]
Grammarly changed its heading formatting. Now Grammarly's h1 is literally ``<h1></h1>`` in the HTML, whereas it used to be <h2></h2>. I think that's the cause of the problem. The extension currently doesn't work.

**Comment by brunoluiz** [comment]
It seems there is a pull request with a patch already. I am planning to do some tests in the evening and release this.

> Is there a log I can check to help troubleshoot?

This is my fault of not having an issue template or something similar. I will try to sort some basic template as well for future issues.

**Comment by brunoluiz** [comment]
Ok, I pushed `2.1.1` version which includes the mentioned patch. It should land on Chrome Web Store at some point.
