### ISSUE TITLE
grammarly hyperlink to markdown - use link not note

### ISSUE THREAD

**Issue by philooo2** [brunoluiz/grammarly-markdown-extension#35]
currnelty you convert grammarly hyperlink into note 

[text][1]
[1]: http://google.com

why not using the hyperlink regular syntax

[text](http://google.com)

Thank so much for the plugin it is awesome, just would want ot to work with my CMS  ;)

**Comment by sinaatalay** [comment]
- Options
    - Choose Link Style:
        - Inlined
    - Save

Done :)
